// Minimal ABIs for on-chain calls (subset of each contract's external interface).
// Full ABIs are generated by `hardhat compile` into contracts/artifacts/.
export const ADDRESSES = {
  // filled from contracts/deployments.json after `npm run deploy:local`
  token: import.meta.env.VITE_TOKEN_ADDRESS || "",
  staking: import.meta.env.VITE_STAKING_ADDRESS || "",
  governance: import.meta.env.VITE_GOVERNANCE_ADDRESS || "",
  marketplace: import.meta.env.VITE_MARKETPLACE_ADDRESS || "",
};

export const TOKEN_ABI = [
  "function balanceOf(address) view returns (uint256)",
  "function totalSupply() view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function approve(address spender, uint256 amount) returns (bool)",
];
export const STAKING_ABI = [
  "function stake(uint256 amount) returns (uint256)",
  "function unstake(uint256 id)",
  "function pendingYield(address user, uint256 id) view returns (uint256)",
];
export const GOVERNANCE_ABI = [
  "function propose(string title, uint256 durationDays) returns (uint256)",
  "function vote(uint256 id, bool support)",
  "function proposalCount() view returns (uint256)",
];
export const MARKETPLACE_ABI = [
  "function license(uint256 id) payable",
  "function listingCount() view returns (uint256)",
];
