[providers]
providers = ["node", "python"]

[phases.setup]
nixPkgs = ["python3", "make", "gcc", "nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx esbuild src/index.ts --bundle=false --platform=node --target=node18 --outfile=dist/index.js"]

[start]
cmd = "node dist/index.js"
