[providers]
providers = ["node", "python"]

[phases.setup]
nixPkgs = ["python3", "make", "gcc", "nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx esbuild src/index.ts --bundle=false --platform=node --target=node18 --format=cjs --outfile=dist/index.js"]

[phases.start]
cmd = "node --max-old-space-size=1024 dist/index.js"
