'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import styles from './ProceduralSkills.module.css';

type Api = (path: string, options?: RequestInit) => Promise<any>;
export type SkillSource = { threadId: string; entryId: string; expectedRevision: number; preview?: string };
type Content = { name: string; description: string; whenToUse: string; instructions: string };
type Release = { id: string; skillId: string; version: number; draftRevision: number; snapshot: Content; contentHash: string; withdrawnAt: string | null; publishedAt: string };
type Skill = { id: string; content: Content; revision: number; status: string; error?: string; projectId: string | null; sourceThreadId: string | null; source: { threadTitle: string; entryId: string; reply?: string; capturedAt: string; conversation?: { role: string; text: string }[]; toolEvidence?: { toolName: string; sha256: string; preview: string }[] }; sourceSha256: string; releases: Release[]; chargeUsd: number | null; billingState: string; locallyActive: boolean };
const empty: Content = { name: '', description: '', whenToUse: '', instructions: '' };
const body = (value: unknown, method = 'POST'): RequestInit => ({ method, body: JSON.stringify(value) });
const errors: Record<string, [string, string]> = {
  SKILL_REVISION_CONFLICT: ['This draft changed. Reload it before saving or publishing.', '草稿已更新，请重新打开后再保存或发布。'],
  SKILL_SELECTION_CONFLICT: ['The selection changed. Refresh and review the selected versions.', '所选版本已更新，请刷新后重新核对。'],
  SKILL_GENERATION_UNRESOLVED: ['A generation or its charge is still unresolved. Refresh its status before trying again.', '生成或费用核对尚未结束，请先刷新查看结果。'],
  SKILL_GENERATION_INTERRUPTED: ['Generation was interrupted. Review its charge and edit the retained draft.', '生成已中断，请核对费用后编辑保留的草稿。'],
  SKILL_GENERATION_FORMAT_INVALID: ['The model did not return a usable draft. You can edit the retained source manually.', '模型未返回可用草稿，可根据保留的来源手动整理。'],
  SKILL_PROJECT_MISMATCH: ['This Skill belongs to another project. Use it in a task in its original project.', '此 Skill 属于另一项目，请在原项目的任务中使用。'],
  SKILL_RELEASE_UNAVAILABLE: ['This version was withdrawn or removed. Refresh and choose an available version.', '此版本已撤回或删除，请刷新并选择可用版本。'],
  SKILL_PUBLISHED_AGENT_FIXED: ['Published Agents keep their fixed instructions. Use Skills in a regular task.', '已发布 Agent 保持固定配置，请在普通任务中使用 Skill。'],
  PI_SESSION_REVISION_CONFLICT: ['The source conversation changed. Select a completed reply again.', '来源会话已更新，请重新选择已完成的回复。'],
  THREAD_RUN_ACTIVE: ['Wait for the task to finish before changing its Skills.', '请等待任务本轮执行完成后，再调整 Skill。'],
  SKILL_STORAGE_LIMIT: ['Your Skill library is full. Remove an unused Skill first.', 'Skill 数量已达上限，请先删除不再使用的内容。'],
  BILLING_PAID_CREDITS_REQUIRED: ['This model requires paid credit. Choose an available model or visit Usage & plan.', '此模型需要付费额度，请选择可用模型或前往用量与套餐。'],
  BILLING_INSUFFICIENT_CREDITS: ['Not enough model credit. Review Usage & plan before generating again.', '模型额度不足，请先查看用量与套餐。'],
  ACCOUNT_SESSION_CHANGED: ['Your account changed. Reopen the Skill library.', '账户已切换，请重新打开 Skill 库。'],
};
const errorText = (error: string, zh: boolean) => errors[error]?.[zh ? 1 : 0] || (zh ? '操作暂未完成，请刷新确认保存状态后重试。' : 'Could not finish this action. Refresh to check the saved state before retrying.');

export function ProceduralSkills({ api, zh, initialSource, onSourceConsumed, onTasks, onBilling }: { api: Api; zh: boolean; initialSource: SkillSource | null; onSourceConsumed: () => void; onTasks: () => void; onBilling: () => void }) {
  const t = (en: string, cn: string) => zh ? cn : en;
  const apiRef = useRef(api); apiRef.current = api;
  const alive = useRef(false), generation = useRef(0), listSequence = useRef(0), sourceSequence = useRef(0), acting = useRef(false), requestKey = useRef<{ value: string; key: string } | null>(null);
  const [skills, setSkills] = useState<Skill[]>([]), [threads, setThreads] = useState<any[]>([]), [models, setModels] = useState<any[]>([]), [projects, setProjects] = useState<any[]>([]);
  const [selected, setSelected] = useState<Skill | null>(null), [draft, setDraft] = useState<Content>(empty), [reviewed, setReviewed] = useState(false);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState(''), [confirmation, setConfirmation] = useState('');
  const [creating, setCreating] = useState(Boolean(initialSource)), [source, setSource] = useState<SkillSource | null>(initialSource), [turns, setTurns] = useState<any[]>([]), [sourceLoading, setSourceLoading] = useState(false);
  const [brief, setBrief] = useState(''), [model, setModel] = useState(''), [maximumUsd, setMaximumUsd] = useState(.1);
  const request = useCallback(async (path: string, options?: RequestInit) => { const response = await apiRef.current(path, options); if (response?.success === false || response?.error) throw new Error(response.error || 'REQUEST_FAILED'); return response.data; }, []);
  const refresh = useCallback(async () => { const sequence = ++listSequence.current; setLoading(true); try { const rows = await request('/procedural-skills'); if (alive.current && sequence === listSequence.current) { setSkills(rows); setError(''); } } catch (caught: any) { if (alive.current && sequence === listSequence.current) setError(caught.message); } finally { if (alive.current && sequence === listSequence.current) setLoading(false); } }, [request]);
  useEffect(() => {
    alive.current = true; void refresh();
    Promise.all([request('/threads?limit=100'), request('/desktop/models'), request('/projects')]).then(([threadRows, modelRows, projectRows]) => {
      if (!alive.current) return; setThreads(threadRows); setModels(modelRows); setProjects(projectRows || []);
      setModel(current => current || modelRows.find((item: any) => item.available && item.tier === 'lightweight')?.id || modelRows.find((item: any) => item.available)?.id || '');
    }).catch(caught => { if (alive.current) setError(caught.message); });
    return () => { alive.current = false; generation.current++; listSequence.current++; sourceSequence.current++; };
  }, [refresh, request]);
  useEffect(() => { if (initialSource) { setSource(initialSource); setCreating(true); onSourceConsumed(); } }, [initialSource, onSourceConsumed]);
  const select = async (id: string) => {
    const sequence = ++generation.current; setLoading(true); setError(''); setConfirmation('');
    try { const skill = await request(`/procedural-skills/${id}`); if (!alive.current || sequence !== generation.current) return; sourceSequence.current++; setSourceLoading(false); setSelected(skill); setDraft({ ...empty, ...skill.content }); setReviewed(false); setCreating(false); }
    catch (caught: any) { if (alive.current && sequence === generation.current) setError(caught.message); }
    finally { if (alive.current && sequence === generation.current) setLoading(false); }
  };
  const chooseThread = async (id: string) => {
    const sequence = ++sourceSequence.current; setSourceLoading(true); setSource(null); setTurns([]); setError('');
    try { const state = await request(`/threads/${id}/pi-session/exploration`); if (!alive.current || sequence !== sourceSequence.current) return; setTurns(state.turns); setSource({ threadId: id, expectedRevision: state.revision, entryId: state.turns[0]?.id || '', preview: state.turns[0]?.text || '' }); }
    catch (caught: any) { if (alive.current && sequence === sourceSequence.current) setError(caught.message); }
    finally { if (alive.current && sequence === sourceSequence.current) setSourceLoading(false); }
  };
  const act = async (label: string, action: () => Promise<void>) => { if (acting.current) return; acting.current = true; generation.current++; setBusy(label); setError(''); setNotice(''); try { await action(); } catch (caught: any) { if (alive.current) setError(caught.message); } finally { acting.current = false; if (alive.current) { setBusy(''); setLoading(false); } } };
  const acceptSkill = (skill: Skill) => { if (!alive.current) return; setSelected(skill); setDraft({ ...empty, ...skill.content }); setReviewed(false); setConfirmation(''); };
  const scope = (id: string | null) => id ? (projects.find(project => project.id === id)?.name || t('Original project', '原项目')) : t('Tasks without a project', '未归属项目的任务');
  const dirty = selected && JSON.stringify(draft) !== JSON.stringify({ ...empty, ...selected.content });
  const valid = Object.values(draft).every(value => value.trim());
  const locked = Boolean(busy) || selected?.status === 'generating' || ['pending', 'unknown', 'review_required'].includes(selected?.billingState || '');
  return <section className={styles.workspace} aria-label={t('Skill library', 'Skill 库')}>
    <header className={styles.header}><div><p className={styles.eyebrow}>FORGE / SKILLS</p><h1>{t('Keep the method. Improve the next task.', '把经验，变成下一次的方法。')}</h1><p>{t('Turn a completed reply into a draft, review it, then choose a fixed version for a task.', '从已完成的回复整理草稿，经你审核后发布，再为任务选择固定版本。')}</p></div><button className={styles.primary} disabled={Boolean(busy)} onClick={() => { generation.current++; sourceSequence.current++; setLoading(false); setSourceLoading(false); setCreating(true); setSource(null); setTurns([]); setError(''); setNotice(''); }}>＋ {t('Create from a task', '从任务整理 Skill')}</button></header>
    {error && <p role="alert" className={styles.error}>{errorText(error, zh)}</p>}{notice && <p role="status" className={styles.notice}>{notice}</p>}
    <div className={styles.layout}><aside className={styles.sidebar}><div className={styles.listTitle}><h2>{t('Your methods', '我的方法')}</h2><button disabled={Boolean(busy) || loading} onClick={() => void refresh()}>{loading ? t('Loading…', '读取中…') : t('Refresh', '刷新')}</button></div>
      {!skills.length && !loading && <p className={styles.muted}>{t('No Skills yet. Start with a task worth repeating.', '还没有 Skill，从值得复用的任务开始。')}</p>}
      {skills.map(skill => <button className={styles.skillLink} aria-current={selected?.id === skill.id && !creating ? 'true' : undefined} disabled={Boolean(busy)} key={skill.id} onClick={() => void select(skill.id)}><strong>{skill.content.name || t('Draft from a task', '任务经验草稿')}</strong><span>{skill.status === 'generating' ? t('Generating', '生成中') : skill.status === 'failed' ? t('Needs attention', '需要处理') : skill.releases.some(release => !release.withdrawnAt) ? t('Published', '已发布') : t('Draft', '草稿')} · {scope(skill.projectId)}</span></button>)}
    </aside><div className={styles.detail}>
      {creating ? <form className={styles.editor} onSubmit={event => { event.preventDefault(); if (!source) return; void act('generate', async () => {
        const payload = { threadId: source.threadId, entryId: source.entryId, expectedRevision: source.expectedRevision, brief, model, maximumUsd }; const signature = JSON.stringify(payload);
        if (requestKey.current?.value !== signature) requestKey.current = { value: signature, key: crypto.randomUUID() };
        const skill = await request('/procedural-skills', { ...body(payload), headers: { 'Idempotency-Key': requestKey.current.key } });
        requestKey.current = null; if (!alive.current) return; acceptSkill(skill); setCreating(false); setBrief(''); if (skill.status === 'failed') setError(skill.error || 'SKILL_GENERATION_FAILED'); else setNotice(t('Draft saved. Review its source, applicability and instructions before publishing.', '草稿已保存，请核对来源、适用条件与操作步骤后再发布。')); await refresh();
      }); }}>
        <p className={styles.eyebrow}>{t('01 / CAPTURE EXPERIENCE', '01 / 整理任务经验')}</p><h2>{t('Start with evidence.', '从有依据的任务开始。')}</h2>
        <label>{t('Source task', '来源任务')}<select disabled={Boolean(busy) || sourceLoading} value={source?.threadId || ''} onChange={event => void chooseThread(event.target.value)}><option value="" disabled>{t('Choose a recent task', '选择最近的任务')}</option>{source && !threads.some(thread => thread.id === source.threadId) && <option value={source.threadId}>{t('Selected task', '已选任务')}</option>}{threads.map(thread => <option key={thread.id} value={thread.id}>{thread.title}</option>)}</select></label>
        {sourceLoading && <p role="status">{t('Reading completed replies…', '正在读取已完成的回复…')}</p>}
        {source && <><label>{t('Completed reply', '已完成的回复')}<select disabled={Boolean(busy)} value={source.entryId} onChange={event => { const turn = turns.find(item => item.id === event.target.value); setSource({ ...source, entryId: event.target.value, preview: turn?.text || '' }); }}>{!turns.length && source.entryId && <option value={source.entryId}>{source.preview?.slice(0, 90) || t('Selected reply', '所选回复')}</option>}{turns.map(turn => <option key={turn.id} value={turn.id}>{turn.text.slice(0, 90)}</option>)}</select></label>{!source.entryId && <p className={styles.muted}>{t('This task has no completed reply yet.', '此任务还没有已完成的回复。')}</p>}{source.preview && <details className={styles.source}><summary>{t('Read the original reply', '查看原始回复')}</summary><pre>{source.preview}</pre></details>}</>}
        <label>{t('What should this method help with?', '希望复用什么方法？')}<textarea required maxLength={3000} rows={3} value={brief} disabled={Boolean(busy)} onChange={event => setBrief(event.target.value)} placeholder={t('Describe the repeatable job and when it should be used…', '描述可重复的工作，以及应当在什么情况下使用…')} /></label>
        <div className={styles.row}><label>{t('Drafting model', '草稿模型')}<select value={model} disabled={Boolean(busy)} onChange={event => setModel(event.target.value)}>{models.map(item => <option key={item.id} value={item.id} disabled={!item.available}>{item.name}{!item.available ? t(' · credit required', ' · 需要额度') : ''}</option>)}</select></label><label>{t('Generation budget (USD)', '生成预算（美元）')}<input type="number" min="0.01" max="2" step="0.01" required value={maximumUsd} disabled={Boolean(busy)} onChange={event => setMaximumUsd(Number(event.target.value))} /></label></div>
        <p className={styles.muted}>{t('Generation uses model credit, up to this budget. The draft retains the original reply and selected source evidence. Review private details and applicability before publishing. Access stays within the source project.', '整理草稿会消耗模型额度，不超过所设预算。草稿保留原始回复与来源证据；发布前请检查隐私信息与适用条件。使用范围保持在来源项目内。')}</p>
        <div className={styles.actions}><button className={styles.primary} disabled={Boolean(busy) || !source?.entryId || !brief.trim() || !model}>{busy === 'generate' ? t('Generating draft…', '正在整理草稿…') : t('Generate draft', '生成草稿')}</button><button type="button" disabled={Boolean(busy)} onClick={() => { sourceSequence.current++; setSourceLoading(false); setCreating(false); }}>{t('Cancel', '取消')}</button><button type="button" onClick={onBilling}>{t('Usage & plan', '用量与套餐')} ↗</button></div>
      </form> : selected ? <>
        <div className={styles.detailHeader}><div><p className={styles.eyebrow}>{t('EDITABLE DRAFT', '可编辑草稿')} · r{selected.revision}</p><h2>{selected.content.name || t('Task experience draft', '任务经验草稿')}</h2></div><span className={styles.badge}>{scope(selected.projectId)}</span></div>
        <p className={styles.muted}>{t('Generation charge', '本次生成费用')}: {selected.chargeUsd === null ? t('not settled / not recorded', '未结算或未记录') : '$' + selected.chargeUsd.toFixed(6)} · {t('Published versions stay fixed when you edit this draft.', '编辑草稿不会改变已发布版本。')}</p>
        {selected.status === 'generating' && <div className={styles.notice}><p>{t('Generation may still be running. Refresh this draft to recover its result. If an interrupted request has settled, recover it before editing.', '生成可能仍在进行。刷新草稿可恢复结果；若请求已中断且费用已核对，可恢复为可编辑草稿。')}</p><div className={styles.actions}><button disabled={Boolean(busy)} onClick={() => void select(selected.id)}>{t('Reload draft', '刷新草稿')}</button><button disabled={Boolean(busy) || selected.locallyActive} onClick={() => void act('recover', async () => { acceptSkill(await request(`/procedural-skills/${selected.id}/recover`, body({}))); await refresh(); })}>{t('Recover interrupted draft', '恢复中断草稿')}</button></div></div>}
        {selected.error && <p className={styles.error}>{errorText(selected.error, zh)}</p>}
        <details className={styles.source}><summary>{t('Source reply & evidence', '来源回复与证据')} · {selected.source.threadTitle}</summary>{!selected.sourceThreadId && <p>{t('The original task was removed. This reviewed source snapshot is retained with the Skill.', '原任务已删除，此 Skill 保留了整理时的来源快照。')}</p>}<pre>{selected.source.reply}</pre>{selected.source.toolEvidence?.map((proof, index) => <details key={index}><summary>{proof.toolName}</summary><pre>{proof.preview}</pre><small>SHA-256: {proof.sha256}</small></details>)}<small>{t('Captured', '保存时间')}: {selected.source.capturedAt}<br />SHA-256: {selected.sourceSha256}</small></details>
        <form className={styles.editor} onSubmit={event => { event.preventDefault(); void act('save', async () => { acceptSkill(await request(`/procedural-skills/${selected.id}`, body({ ...draft, expectedRevision: selected.revision }, 'PATCH'))); if (alive.current) setNotice(t('Draft saved. Review this revision before publishing.', '草稿已保存，请审核此修订后再发布。')); await refresh(); }); }}>
          {([['name', t('Skill name', 'Skill 名称'), 120], ['description', t('What it does', '作用说明'), 500], ['whenToUse', t('Applicability & exclusions', '适用条件与不适用情况'), 2000], ['instructions', t('Procedure, checks & approval boundaries', '操作步骤、验收方式与授权边界'), 12000]] as [keyof Content, string, number][]).map(([field, label, limit]) => <label key={field}>{label}{field === 'name' ? <input required maxLength={limit} disabled={locked} value={draft[field]} onChange={event => { setDraft(current => ({ ...current, [field]: event.target.value })); setReviewed(false); }} /> : <textarea required rows={field === 'instructions' ? 12 : 3} maxLength={limit} disabled={locked} value={draft[field]} onChange={event => { setDraft(current => ({ ...current, [field]: event.target.value })); setReviewed(false); }} />}</label>)}
          <button disabled={locked || !dirty || !valid}>{busy === 'save' ? t('Saving…', '保存中…') : t('Save draft', '保存草稿')}</button>
        </form>
        <div className={styles.review}><p className={styles.eyebrow}>{t('REVIEW & PUBLISH', '审核与发布')}</p><label className={styles.checkbox}><input type="checkbox" checked={reviewed} disabled={locked || Boolean(dirty) || !valid} onChange={event => setReviewed(event.target.checked)} /><span>{t('I reviewed the source, removed task-specific private details, and checked applicability and instructions.', '我已核对来源，移除不应复用的私密信息，并检查适用条件与操作步骤。')}</span></label><p className={styles.muted}>{t('Publishing makes a version available in your own project. It grants no new permissions and does not prove the method has been tested.', '发布后可在自己的同项目任务中选用此版本，不会增加权限，也不代表方法已通过独立测试。')}</p><button className={styles.primary} disabled={locked || Boolean(dirty) || !reviewed || !valid || selected.releases.some(release => release.draftRevision === selected.revision)} onClick={() => void act('publish', async () => { await request(`/procedural-skills/${selected.id}/publish`, body({ expectedRevision: selected.revision, reviewed: true })); acceptSkill(await request(`/procedural-skills/${selected.id}`)); if (alive.current) setNotice(t('Version published. Select it from Skills in a task to use it.', '版本已发布，在任务的 Skill 选项中选择后即可使用。')); await refresh(); })}>{t('Publish reviewed version', '发布已审核版本')}</button>{dirty && <p className={styles.muted}>{t('Save your changes before reviewing.', '请先保存修改，再审核发布。')}</p>}</div>
        <div className={styles.versions}><h3>{t('Published versions', '已发布版本')}</h3>{!selected.releases.length && <p className={styles.muted}>{t('No published version yet.', '尚未发布版本。')}</p>}{selected.releases.map(release => <article key={release.id}><div className={styles.releaseHeading}><strong>v{release.version} · {release.snapshot.name}</strong><span className={styles.badge}>{release.withdrawnAt ? t('Withdrawn', '已撤回') : t('Available', '可使用')}</span></div><p>{release.snapshot.description}</p><details className={styles.source}><summary>{t('Inspect this fixed version', '查看此固定版本')}</summary><p>{release.snapshot.whenToUse}</p><pre>{release.snapshot.instructions}</pre><small>SHA-256: {release.contentHash}</small></details>{!release.withdrawnAt && <button disabled={Boolean(busy)} onClick={() => setConfirmation(release.id)}>{t('Withdraw version', '撤回版本')}</button>}{confirmation === release.id && <div className={styles.confirm}><p>{t('Withdraw this version from future task replies? Existing history stays visible. Active tasks must finish first.', '撤回后，后续任务回复将不再加载此版本，历史记录仍保留。正在运行的任务需先完成。')}</p><div className={styles.actions}><button disabled={Boolean(busy)} onClick={() => void act('withdraw', async () => { await request(`/procedural-skills/${selected.id}/releases/${release.id}/withdraw`, body({})); acceptSkill(await request(`/procedural-skills/${selected.id}`)); await refresh(); })}>{t('Confirm withdrawal', '确认撤回')}</button><button disabled={Boolean(busy)} onClick={() => setConfirmation('')}>{t('Keep version', '保留版本')}</button></div></div>}</article>)}</div>
        <div className={styles.danger}><button disabled={locked} onClick={() => setConfirmation('delete')}>{t('Delete Skill', '删除 Skill')}</button>{confirmation === 'delete' && <div className={styles.confirm}><p>{t('Delete this draft, its published versions and retained source snapshot? Tasks will stop loading it; existing conversation history is retained.', '删除草稿、所有发布版本及保留的来源快照？任务将不再加载此 Skill，已有会话历史仍保留。')}</p><div className={styles.actions}><button disabled={Boolean(busy)} onClick={() => void act('delete', async () => { await request(`/procedural-skills/${selected.id}`, body({ expectedRevision: selected.revision }, 'DELETE')); if (!alive.current) return; setSelected(null); setConfirmation(''); await refresh(); })}>{t('Confirm deletion', '确认删除')}</button><button onClick={() => setConfirmation('')}>{t('Cancel', '取消')}</button></div></div>}</div>
      </> : <div className={styles.empty}><div className={styles.methodMark} aria-hidden="true">01 <span>→</span> 02 <span>→</span> ∞</div><h2>{t('Good work deserves a second use.', '让一次好方法，服务更多任务。')}</h2><p>{t('Capture the steps, evidence checks and boundaries behind a useful result. Keep drafts editable and published versions dependable.', '保留有效结果背后的步骤、证据检查和适用边界。草稿可以持续完善，发布版本保持稳定。')}</p><button onClick={onTasks}>{t('Open tasks', '前往任务')} ↗</button></div>}
    </div></div>
  </section>;
}

export function ThreadSkills({ api, threadId, zh, sending, onLibrary }: { api: Api; threadId: string; zh: boolean; sending: boolean; onLibrary: () => void }) {
  const t = (en: string, cn: string) => zh ? cn : en; const apiRef = useRef(api); apiRef.current = api;
  const alive = useRef(false), acting = useRef(false), sequence = useRef(0), container = useRef<HTMLDivElement>(null), trigger = useRef<HTMLButtonElement>(null);
  const [open, setOpen] = useState(false), [data, setData] = useState<any>(null), [ids, setIds] = useState<string[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const refresh = useCallback(async () => { const current = ++sequence.current; try { const result = await apiRef.current(`/threads/${threadId}/skills`); if (!result.success) throw Error(result.error); if (!alive.current || current !== sequence.current) return; setData(result.data); setIds(result.data.selected.filter((item: any) => item.available).map((item: any) => item.id)); setError(''); } catch (caught: any) { if (alive.current && current === sequence.current) setError(caught.message); } }, [threadId]);
  useEffect(() => { alive.current = true; void refresh(); return () => { alive.current = false; sequence.current++; }; }, [refresh]);
  useEffect(() => { if (open && !sending) void refresh(); }, [open, sending, refresh]);
  useEffect(() => {
    if (!open) return;
    const dismiss = (event: PointerEvent) => { if (!acting.current && !container.current?.contains(event.target as Node)) setOpen(false); };
    const escape = (event: KeyboardEvent) => { if (event.key === 'Escape' && !acting.current) { setOpen(false); trigger.current?.focus(); } };
    document.addEventListener('pointerdown', dismiss); document.addEventListener('keydown', escape);
    return () => { document.removeEventListener('pointerdown', dismiss); document.removeEventListener('keydown', escape); };
  }, [open]);
  const choices: Release[] = data ? [...new Map<string, Release>([...data.selected.filter((item: any) => item.available), ...data.available].map((item: Release) => [item.id, item] as [string, Release])).values()] : [];
  return <div ref={container} className={styles.taskSkills}><button ref={trigger} type="button" aria-expanded={open} onClick={() => setOpen(value => !value)}>{t('Skills', 'Skill')} {data?.selected?.filter((item: any) => item.available).length || ''}<span aria-hidden="true"> {open ? '−' : '+'}</span></button>{open && <div className={styles.taskPanel} role="region" aria-label={t('Task Skills', '任务 Skill')}>
    <div className={styles.listTitle}><strong>{t('Use a reviewed method', '选用已审核的方法')}</strong><button type="button" aria-label={t('Close Skill selection', '关闭 Skill 选择')} onClick={() => setOpen(false)}>×</button></div>
    <p className={styles.muted}>{t('Choose up to four fixed versions. Applies on the next message; no model call now.', '最多选择 4 个固定版本，下次发消息时生效；此操作不会调用模型。')}</p>
    {error && <p className={styles.error} role="alert">{errorText(error, zh)}</p>}{notice && <p className={styles.notice} role="status">{notice}</p>}
    {!data && !error && <p role="status">{t('Loading…', '读取中…')}</p>}
    {data?.fixedAgent ? <p className={styles.muted}>{t('This published Agent uses its fixed configuration.', '此已发布 Agent 使用固定配置。')}</p> : <>{!choices.length && data && <p className={styles.muted}>{t('No published Skills in this project yet.', '此项目尚无已发布的 Skill。')}</p>}{data?.selected.some((item: any) => !item.available) && <p className={styles.muted}>{t('An earlier selection is unavailable and will not load. Save to clear it.', '先前选择的部分版本已不可用，不会被加载。保存选择可清除这些记录。')}</p>}{choices.map(release => <label key={release.id} className={styles.skillChoice}><input type="checkbox" checked={ids.includes(release.id)} disabled={busy || sending || (!ids.includes(release.id) && ids.length >= 4 && !choices.some(item => ids.includes(item.id) && item.skillId === release.skillId))} onChange={event => setIds(previous => event.target.checked ? [...previous.filter(id => choices.find(item => item.id === id)?.skillId !== release.skillId), release.id] : previous.filter(id => id !== release.id))} /><span><strong>{release.snapshot.name} · v{release.version}</strong><small>{release.snapshot.description}</small></span></label>)}
      <button type="button" className={styles.primary} disabled={busy || sending || !data} onClick={async () => { if (acting.current) return; acting.current = true; sequence.current++; setBusy(true); setError(''); setNotice(''); try { const response = await apiRef.current(`/threads/${threadId}/skills`, body({ releaseIds: ids, expectedRevision: data.revision }, 'PUT')); if (!response.success) throw Error(response.error); if (!alive.current) return; setData(response.data); setNotice(t('Selection saved. It applies to the next message.', '选择已保存，下次发消息时生效。')); } catch (caught: any) { if (alive.current) setError(caught.message); } finally { acting.current = false; if (alive.current) setBusy(false); } }}>{t('Save selection', '保存选择')}</button></>}
    <div className={styles.actions}><button type="button" disabled={busy} onClick={() => void refresh()}>{t('Refresh', '刷新')}</button><button type="button" onClick={onLibrary}>{t('Open Skill library', '打开 Skill 库')} ↗</button></div>
  </div>}</div>;
}
