{{- range $service := .Values.services -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $service.name }}-sa
  namespace: {{ $.Values.global.namespace | default "forge" }}
  labels:
    app: {{ $service.name }}
    environment: {{ $.Values.global.environment }}
---
{{- end }}
