import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import "./database/db.js";
import { startChainListener } from "./services/chainListener.js";
import { rateLimit, secureHeaders, errorHandler } from "./middleware/security.js";
import { metricsMiddleware } from "./middleware/metrics.js";
import { requestLogger, logger } from "./lib/logger.js";
import metrics from "./routes/metrics.js";
import auth from "./routes/auth.js";
import users from "./routes/users.js";
import generate from "./routes/generate.js";
import insights from "./routes/insights.js";
import data from "./routes/data.js";
import bonds from "./routes/bonds.js";
import predictions from "./routes/predictions.js";
import market from "./routes/market.js";
import stats from "./routes/stats.js";
import leaderboard from "./routes/leaderboard.js";
import inference from "./routes/inference.js";
import events from "./routes/events.js";
import admin from "./routes/admin.js";
import chain from "./routes/chain.js";
import notifications from "./routes/notifications.js";
import analytics from "./routes/analytics.js";
import subnets from "./routes/subnets.js";
import keys from "./routes/keys.js";
import governance from "./routes/governance.js";
import staking from "./routes/staking.js";
import burn from "./routes/burn.js";
import referrals from "./routes/referrals.js";
import achievements from "./routes/achievements.js";
import search from "./routes/search.js";
import price from "./routes/price.js";
import presence from "./routes/presence.js";
import exportR from "./routes/export.js";
import activity from "./routes/activity.js";
import docs from "./routes/docs.js";
import chainEvents from "./routes/chainEvents.js";
import digest from "./routes/digest.js";
import prefs from "./routes/prefs.js";
import treasury from "./routes/treasury.js";
import treasuryMultisig from "./routes/treasuryMultisig.js";
import webhooks from "./routes/webhooks.js";
import status from "./routes/status.js";
import backup from "./routes/backup.js";
import faucet from "./routes/faucet.js";
import news from "./routes/news.js";
import { startWebhooks } from "./services/webhooks.js";
import { startIndexer } from "./services/indexer.js";
import { startPriceFeed } from "./services/price.js";
import { startBurnEngine } from "./services/burnEngine.js";
import { initChain } from "./services/chain.js";

dotenv.config({ path: "../.env" });
const app = express();
app.use(cors());
app.use(express.json({ limit: "1mb" }));
app.use(secureHeaders);
app.use(metricsMiddleware);
app.use(requestLogger);
app.use("/api", rateLimit({ windowMs: 60000, max: 300 }));

app.use("/metrics", metrics);
app.use("/status", status);
app.get("/health", (_req, res) => res.json({ ok: true, brand: process.env.BRAND || "Minera" }));
app.use("/api/auth", auth);
app.use("/api/users", users);
app.use("/api/generate", generate);
app.use("/api/insights", insights);
app.use("/api/data", data);
app.use("/api/bonds", bonds);
app.use("/api/predictions", predictions);
app.use("/api/market", market);
app.use("/api/stats", stats);
app.use("/api/leaderboard", leaderboard);
app.use("/api/events", events);
app.use("/api/admin", admin);
app.use("/api/admin", backup);
app.use("/api/faucet", faucet);
app.use("/api/news", news);
app.use("/api/chain", chain);
app.use("/api/notifications", notifications);
app.use("/api/analytics", analytics);
app.use("/api/subnets", subnets);
app.use("/api/keys", keys);
app.use("/api/governance", governance);
app.use("/api/staking", staking);
app.use("/api/burn", burn);
app.use("/api/referrals", referrals);
app.use("/api/achievements", achievements);
app.use("/api/search", search);
app.use("/api/price", price);
app.use("/api/presence", presence);
app.use("/api/export", exportR);
app.use("/api/activity", activity);
app.use("/api/docs", docs);
app.use("/api/chain/events", chainEvents);
app.use("/api/digest", digest);
app.use("/api/prefs", prefs);
app.use("/api/treasury", treasury);
app.use("/api/treasury-actions", treasuryMultisig);
app.use("/api/webhooks", webhooks);
app.use("/v1", inference);

app.use(errorHandler);

const PORT = process.env.PORT || 4000;
app.listen(PORT, () => {
  console.log(`✦ Minera API on http://localhost:${PORT}`);
  startChainListener();
  initChain();
  startBurnEngine(60000);
  startPriceFeed(5000);
  startIndexer();
  startWebhooks();
});
