[providers]
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --omit=dev --prefer-offline || npm install --omit=dev"]

[phases.build]
cmds = ["echo 'dist pre-built'"]

[start]
cmd = "node --max-old-space-size=4096 dist/index.js"
