[providers]
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'using committed CJS dist'"]

[start]
cmd = "node --max-old-space-size=4096 dist/index.js"
