'use client';
import React,{useEffect,useState} from 'react';
import {useUiLanguage,type UiLanguage} from '../../lib/ui-language';
import {publicOffer} from '../../lib/public-offer';
import styles from './page.module.css';
export default function LandingClient({initialLanguage}:{initialLanguage:UiLanguage}){
 const[uiLanguage,setUiLanguage]=useUiLanguage(initialLanguage);
 const[purchasesEnabled,setPurchasesEnabled]=useState(false);
 useEffect(()=>{const controller=new AbortController();fetch('/api/billing/availability',{cache:'no-store',signal:controller.signal}).then(response=>response.ok?response.json():null).then(data=>{if(!controller.signal.aborted)setPurchasesEnabled(data?.purchasesEnabled===true);}).catch(()=>{});return()=>controller.abort();},[]);
 const zh=uiLanguage==='zh';
 const t=(en:string,cn:string)=>zh?cn:en,language=zh?'zh':'en',signup='/register?lang='+language,login='/login?lang='+language;
 const changeLanguage=()=>setUiLanguage(zh?'en':'zh');
 const steps=[
 [t('Describe the work.','说清你想完成的工作。'),t('Explain the outcome, constraints and how you like things done. Refine the draft instructions in conversation.','描述目标、限制和你的工作方式，通过对话完善 Agent 指令。')],
 [t('Give it your context.','让它理解你的资料。'),t('Organize files into folders. Connect the sources that belong to this Agent, with references you can inspect.','将文件整理到文件夹，为 Agent 绑定所需资料，并检查回答引用的来源。')],
 [t('Set your standard.','用你的标准测评。'),t('Write test questions and explicit checks. Run them within a chosen budget before publishing a version.','定义测试问题与检查规则，在设定预算内完成测评，再发布固定版本。')],
 [t('Put it to work.','让成果真正落地。'),t('Start tasks from the published version. Review saved files, check their contents and see what the task cost.','用已发布版本启动任务，检查保存的文件、验收内容，并查看实际费用。')]];
 const faqs=[
 [t('What can I create with Forge?','Forge 可以创建什么？'),t('Create personal Agents for repeatable work such as source-based analysis, document drafting and structured reports. You define the instructions, sources and evaluation rules. Results still need your review.','你可以为资料分析、文档起草、结构化报告等重复工作创建个人 Agent，自定义指令、资料和测评规则。重要结果仍需要你复核。')],
 [t('Do I need a model API key?','需要自己准备模型 API Key 吗？'),t('No separate model key is needed for managed Forge models. Some models are currently free, subject to provider limits; paid models use your Forge credit at different rates.','使用 Forge 托管模型无需额外模型密钥。部分模型当前免费，受供应商限额约束；付费模型按不同费率扣减 Forge 额度。')],
 [t('How are model requests charged?','模型请求如何计费？'),t('Currently free models use no Forge credit. Paid models charge verified OpenRouter inference cost × 1.25, including any provider-billed reasoning, caching and other items. The model picker shows reference prices; usage history shows settled charges. Unreconciled costs remain pending.','当前免费模型不扣 Forge 额度。付费模型按已核对的 OpenRouter 推理成本 × 1.25 扣减，包含供应商计费的推理、缓存等项目。模型选择器显示参考价格，用量记录显示实际结算费用；待核对费用保持待结算。')],
 [t('What happens when my credit runs out?','额度用完后会发生什么？'),purchasesEnabled?t('Paid model requests stop when available credit cannot cover the required reservation. Currently free models can still run, subject to provider limits and availability. Additional credit starts at $20; there is no automatic top-up. Monthly plan credit expires at the end of its billing period.','额度不足时，付费模型请求会停止；当前免费模型仍可使用，受供应商限额及可用性约束。额外额度最低充值 $20，不会自动充值。套餐月度额度在对应账期结束时到期。'):t('Paid model requests stop when available credit cannot cover the required reservation. Currently free models can still run, subject to provider limits and availability. New credit purchases are temporarily unavailable; there is no automatic top-up. Existing monthly plan credit expires at the end of its billing period.','额度不足时，付费模型请求会停止；当前免费模型仍可使用，受供应商限额及可用性约束。新购额度暂时不可用，也不会自动充值。已有套餐的月度额度在对应账期结束时到期。')],
 [t('Can I use Forge on my computer?','可以在电脑本地使用吗？'),t('Forge Desktop is in private preview. It connects to your Forge account and runs local tools on folders you approve. Relevant task content is sent to the chosen model provider for inference. Public Windows and macOS downloads are not available yet.','Forge 桌面端目前处于内测。它连接你的 Forge 账号，在你授权的文件夹中运行本地工具；推理所需的任务内容会发送给所选模型供应商。目前尚未开放 Windows 和 macOS 公共下载。')],
 [t('Can I cancel my subscription?','可以取消订阅吗？'),t('Use the secure billing portal in Usage & plan to cancel renewal. Paid access continues through the current paid period. Check the final price and applicable taxes in Checkout before paying.','在“用量与套餐”的安全账单门户中可以取消续费。已付费权益持续到当前已付账期结束。付款前请在结账页面核对最终价格和适用税费。')]];
 return <div className={styles.page} lang={zh?'zh-CN':'en'}>
 <a className={styles.skip} href="#main">{t('Skip to content','跳转到正文')}</a>
 <header className={styles.header}><a href={'/landing?lang='+language} className={styles.brand} aria-label="Forge"><span>F</span>Forge</a><nav aria-label={t('Main navigation','主导航')}><a href="#workflow">{t('How it works','使用流程')}</a><a href="#pricing">{t('Pricing','价格')}</a><a href="#questions">{t('Questions','常见问题')}</a></nav><div className={styles.account}><button onClick={changeLanguage} type="button" aria-label={t('Switch to Chinese','切换为英文')}>{zh?'EN':'中文'}</button><a href={login}>{t('Sign in','登录')} ↗</a></div></header>
 <main id="main"><section className={styles.hero}>
 <div className={styles.kicker}><span/> FORGE / {t('THE PERSONAL AGENT WORKSPACE','你的专属 AGENT 工作区')}</div>
 <div className={styles.heroGrid}><h1>{t('Your expertise.','你的专业，')}<em>{t('An Agent','成为 Agent。')}<br/>{t('that delivers.','交付真实成果。')}</em></h1><div className={styles.heroCopy}><p>{t('Turn the way you work into an Agent of your own. Bring your sources, test your standards, and get to a result you can review.','把你的工作方法，变成自己的 Agent。带上你的资料，用你的标准测评，交付可以检查的成果。')}</p><a className={styles.primary} href={signup}>{t('Create your workspace','创建你的工作区')} <span>↗</span></a><span className={styles.micro}>{t('Free account · Free models available now · Provider limits apply','免费注册 · 当前可用免费模型 · 受供应商限额约束')}</span></div></div>
 <div className={styles.ribbon}><span>{t('YOUR SOURCES','你的资料')}</span><i>→</i><span>{t('YOUR AGENT','你的 AGENT')}</span><i>→</i><span>{t('YOUR STANDARD','你的标准')}</span><i>→</i><span>{t('REAL DELIVERABLES','真实交付物')}</span></div></section>
 <section className={styles.proof} aria-labelledby="proof-title"><div className={styles.proofHeading}><div><p className={styles.kicker}>01 / {t('FROM INTENT TO EVIDENCE','从想法到可验收成果')}</p><h2 id="proof-title">{t('Done has a definition.','完成，有据可验。')}</h2></div><p>{t('Saved files. Explicit checks. Actual task cost. A result you can inspect, download and use again.','文件已保存，要求可检查，费用有记录。成果可以查看、下载，也能成为下次工作的起点。')}</p></div><figure className={styles.product}><div className={styles.windowBar}><span/><span/><span/><p>Forge / {t('Task workspace','任务工作区')}</p><b>{t('Actual product view','实机界面')}</b></div><img src={zh?'/landing/task-acceptance-zh.png':'/landing/task-acceptance-en.png'} width={zh?390:1440} height={1000} alt={t('Forge showing four passed checks for a chart, CSV rows, total and JSON field. Internal sample data.','Forge 图表文件、CSV 行数、净收入合计和 JSON 字段四项验收通过。内部示例数据。')} loading="eager"/><figcaption>{t('Internal sample workspace · Real saved outputs · Checks verify file content, not factual accuracy or code execution.','内部示例工作区 · 真实保存的产物 · 检查验证文件内容，不证明事实准确性或代码运行行为。')}</figcaption></figure></section>
 <section id="workflow" className={styles.workflow}><div className={styles.sectionIntro}><p className={styles.kicker}>02 / {t('A WORKFLOW YOU OWN','属于你的工作流程')}</p><h2>{t('Built around','围绕你的方式，')}<em>{t('your way of working.','建立工作流程。')}</em></h2></div><div className={styles.steps}>{steps.map(([title,body],i)=><article key={i}><span>0{i+1}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></section>
 <section className={styles.foundation}><div><p className={styles.kicker}>03 / {t('MADE FOR REPEATABLE WORK','为重复工作而设计')}</p><h2>{t('Less starting over.','积累你的方法，')}<br/>{t('More building on.','不必每次重来。')}</h2></div><div className={styles.foundationItems}>{[
 [t('A library with a purpose.','让资料为工作所用。'),t('Keep files and folders in your personal library. Bind the right sources to each Agent instead of rebuilding context for every task.','在个人资料库中管理文件与文件夹，为每个 Agent 绑定合适来源，减少重新交代背景。')],
 [t('Versions you can return to.','保留可复用的版本。'),t('Publish a tested version and start a task from it. Later draft edits do not quietly change that task’s pinned instructions.','测评后发布版本并启动任务。后续修改草稿，不会悄悄改变任务已经固定的指令。')],
 [t('A model for the job.','按任务选择模型。'),t('Choose flagship, balanced or lightweight models. Review reference prices before running and actual charges in your shared Forge wallet.','在旗舰、均衡和轻量模型之间选择，运行前查看参考价格，在统一 Forge 钱包中追踪实际消费。')]
 ].map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>
 <section id="pricing" className={styles.pricing}><div className={styles.sectionIntro}><p className={styles.kicker}>04 / {t('CLEAR PRICING','清晰的价格')}</p><h2>{t('Choose your pace.','选择适合你的用量。')}</h2><p>{t('Start with currently free models. Paid monthly plans include model credit, shared by your website and Desktop.','先用当前免费模型开始；付费月套餐包含模型额度，网站与桌面端共用同一个 Forge 钱包。')}</p></div>{!purchasesEnabled&&<p className={styles.purchaseNote} role="status">{t('New paid purchases are temporarily unavailable. Create a free workspace and use currently free models, subject to provider limits and availability.','新购付费套餐和额度暂时不可用。你可以先创建免费工作区，使用当前免费模型；具体以账号内可用状态和供应商限额为准。')}</p>}<div className={styles.plans}><article data-testid="plan-free"><div className={styles.planLabel}>{t('Free','免费')}<span>00</span></div><p className={styles.price}>$0<span>{t('/ month','/ 月')}</span></p><p className={styles.allowance}>{t('Currently free models · no Forge credit','当前免费模型 · 不扣 Forge 额度')}</p><p className={styles.planFor}>{t('Create a workspace without a card. Free model availability and provider limits may change.','无需银行卡即可创建工作区。免费模型的可用状态与供应商限额可能变化。')}</p><ul><li>{t('Agent creation and personal library','创建 Agent 与个人资料库')}</li><li>{t('Task files and delivery checks','任务文件与交付验收')}</li><li>{t('Usage history for each task','查看每项任务的用量记录')}</li></ul><a href={signup}>{t('Start free','免费开始')} ↗</a></article>{publicOffer.plans.map((plan,i)=><article key={plan.id} data-testid={'plan-'+plan.id}><div className={styles.planLabel}>{plan.name}<span>0{i+1}</span></div><p className={styles.price}>${plan.monthlyUsd}<span>{t('/ month','/ 月')}</span></p><p className={styles.allowance}>${plan.includedUsd} {t('monthly model credit','每月模型额度')}</p><p className={styles.planFor}>{[t('For focused, occasional work.','适合专注、低频的工作。'),t('For a regular Agent workflow.','适合日常 Agent 工作流。'),t('For higher personal usage.','适合更高的个人使用量。')][i]}</p><ul><li>{t('Agent creation and personal library','创建 Agent 与个人资料库')}</li><li>{t('Evaluations and published versions','测评与发布版本')}</li><li>{t('Task files and delivery checks','任务文件与交付验收')}</li><li>{t('Shared wallet and usage history','统一钱包与用量记录')}</li></ul><a href={signup}>{purchasesEnabled?t('Get started','开始使用'):t('Create free workspace','创建免费工作区')} ↗</a></article>)}</div><div className={styles.priceNotes}><p>{t('Paid plans are priced in USD and billed monthly. Included credit expires at the end of each billing period. Applicable taxes and the final total are shown at checkout.','付费套餐以美元计价，按月收取。套餐额度在对应账期结束时到期。适用税费与最终总额在结账时显示。')}</p><p>{t('Managed inference: verified OpenRouter cost × 1.25. Additional credit starts at $20. Eligible new accounts may receive a one-time trial of up to $0.10, subject to availability shown in your account.','托管推理按已核对的 OpenRouter 成本 × 1.25 扣减。额外额度最低充值 $20。符合条件的新账号可获得最高 $0.10 的一次性试用额度，是否可领取以账号内显示为准。')}</p></div></section>
 <section id="questions" className={styles.questions}><div><p className={styles.kicker}>05 / {t('A FEW DETAILS','你可能关心')}</p><h2>{t('Before you begin.','开始之前。')}</h2></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
 <section className={styles.closing}><span>F</span><h2>{t('Your next workflow','你的下一个工作流，')}<br/>{t('starts with you.','从你的想法开始。')}</h2><a className={styles.primary} href={signup}>{t('Create your workspace','创建你的工作区')} ↗</a></section>
 </main><footer className={styles.footer}><a href={'/landing?lang='+language} className={styles.brand}>Forge</a><p>© 2026 Forge</p><a href="/privacy">{t('Privacy','隐私政策（英文）')}</a><a href="/terms">{t('Terms','服务条款（英文）')}</a><a href={login}>{t('Sign in','登录')} ↗</a></footer></div>;
}
