services:
  backend:
    build: ./backend
    ports: ["4000:4000"]
    environment:
      - BRAND=Minera
      - PORT=4000
    volumes:
      - dbdata:/app/data
  frontend:
    build: ./frontend
    ports: ["8080:80"]
    depends_on: [backend]
volumes:
  dbdata:
