// Chinese presentation for the AI Tools catalog.
// The platform stays the source of truth for which tools exist and what each one runs;
// this file only translates what a Chinese reader sees. A tool the platform adds later
// still appears, falling back to its English label until a translation lands here.

export type DreamToolText = { label: string; summary: string; inputLabel: string; placeholder: string };

export const DREAM_TOOL_CATEGORY_ZH: Record<string, string> = {
  All: '全部',
  Career: '职业',
  Writing: '写作',
  Finance: '理财',
  Health: '健康',
  Learning: '学习',
  Creative: '创作',
  Legal: '法律',
  Relationships: '关系',
  Productivity: '效率',
  Business: '商业',
  Fun: '趣味',
};

export const DREAM_TOOL_ZH: Record<string, DreamToolText> = {
  resumebuilder: { label: '简历生成', summary: '把零散经历整理成有针对性、能过筛选系统的简历。', inputLabel: '你的经历，或你想应聘的岗位', placeholder: '把工作经历、现有简历，或想匹配的招聘启事贴进来……' },
  coverlettergen: { label: '求职信', summary: '一封具体、读起来像真人写的求职信。', inputLabel: '岗位、公司和你的背景', placeholder: '贴上招聘启事，再写几句你的背景……' },
  interviewcoach: { label: '面试教练', summary: '可能被问到的问题、参考答案，以及你的薄弱环节。', inputLabel: '岗位、层级和你的背景', placeholder: '描述你要面试的岗位，以及相关背景……' },
  salaryneg: { label: '薪资谈判', summary: '一个数字、一套话术，以及可以走人的底线。', inputLabel: 'offer 细节和你的筹码', placeholder: '说明这份 offer、你目前的薪资、所在城市，以及是否有其他 offer……' },
  linkedinopt: { label: 'LinkedIn 动态', summary: '一条不油腻又能被看见的职场动态。', inputLabel: '你想发什么', placeholder: '描述你想发布的消息、心得或成果……' },
  careerpivot: { label: '转行规划', summary: '从现在的位置到目标行业，一条现实可走的路。', inputLabel: '当前岗位和目标领域', placeholder: '描述你现在的岗位、技能，以及想转入的领域……' },
  promotioncase: { label: '晋升材料', summary: '把你的晋升理由写成书面材料。', inputLabel: '你的岗位、层级和近期成果', placeholder: '列出近期成果、负责范围，以及目标层级……' },
  perfreview: { label: '绩效评语', summary: '具体、公允的绩效评价文字。', inputLabel: '你要评价谁、发生了什么', placeholder: '贴上关于这个人、这个周期和交付情况的记录……' },
  offereval: { label: 'Offer 评估', summary: '按真正重要的条件比较一份 offer。', inputLabel: '这份 offer 和你的其他选择', placeholder: '贴上 offer 细节、你目前的状况，以及其他选项……' },
  jobscout96: { label: '找工作参谋', summary: '该去哪里找，以及到了之后该怎么说。', inputLabel: '你的背景和下一步想要什么', placeholder: '描述你的经验、所在地、限制条件和目标岗位……' },
  emailnegotiator: { label: '谈判邮件', summary: '一封既守得住立场又不失礼的谈判邮件。', inputLabel: '你在和谁谈什么', placeholder: '描述当下情况、你的诉求，以及对方的说法……' },
  speechwriter: { label: '演讲稿', summary: '为耳朵而写，不是为纸面而写。', inputLabel: '场合、听众和时长', placeholder: '描述场合、听众、时间限制，以及你想表达什么……' },
  viralhooks: { label: '开头钩子', summary: '十个让人停下来的开头。', inputLabel: '你的主题或草稿', placeholder: '描述主题，或贴上想要配钩子的内容……' },
  coldpitch: { label: '陌生推介', summary: '一封给得出回复理由的陌生推介。', inputLabel: '你要推介给谁、提供什么', placeholder: '描述你的产品或服务，以及你要推介的人或公司……' },
  colddmwriter: { label: '陌生私信', summary: '像真人说话、也真的会有人回的私信。', inputLabel: '你要私信谁、为什么', placeholder: '描述这个人、所在平台，以及你想达成什么……' },
  viralthread: { label: '长帖写作', summary: '有主线的长帖，而不是一串要点。', inputLabel: '你的主题或素材', placeholder: '贴上想改写成长帖的想法、笔记或文章……' },
  captiongen: { label: '配文生成', summary: '按平台调性写的配文，而不是一份到处复制。', inputLabel: '这条内容拍的是什么', placeholder: '描述你要发布的照片、视频或那个瞬间……' },
  newsletterdraft: { label: '邮件周刊', summary: '一期读者愿意读完的内容。', inputLabel: '主题和读者', placeholder: '描述主题、你的读者，以及必须包含的内容……' },
  adcopy94: { label: '广告文案', summary: '围绕一个主张写的广告文案。', inputLabel: '产品、受众和投放渠道', placeholder: '描述产品、面向谁，以及广告投放在哪里……' },
  seowriter94: { label: 'SEO 博客', summary: '写给人读，同时也能被搜到。', inputLabel: '关键词或主题', placeholder: '给出关键词或主题；知道受众的话也一并说明……' },
  financeadvisor: { label: '理财顾问', summary: '关于你财务状况的直接答案。', inputLabel: '你的情况和问题', placeholder: '描述收入、存款、负债，以及你面临的决定……' },
  networthcalc: { label: '净资产测算', summary: '你的资产负债表，以及它说明了什么。', inputLabel: '资产与负债', placeholder: '列出你拥有的和欠下的，金额大致准确即可……' },
  budgetroast: { label: '预算吐槽', summary: '对你消费的一次诚实又好笑的审视。', inputLabel: '你的月度支出', placeholder: '贴上月度预算或各项支出……' },
  firecalc: { label: '财务自由测算', summary: '工作变成可选项的时间点，以及全部假设。', inputLabel: '收入、储蓄率和支出', placeholder: '说明收入、年支出、现有存款和预期收益率……' },
  debtpayoff: { label: '还债计划', summary: '一份带真实日期的还债方案。', inputLabel: '你的各笔负债', placeholder: '逐笔列出余额、利率和最低还款额……' },
  subaudit: { label: '订阅体检', summary: '找出正在悄悄消耗你的订阅。', inputLabel: '你的订阅服务', placeholder: '列出订阅的服务和大致费用……' },
  sidehustle: { label: '副业规划', summary: '一个能塞进你真实时间的副业方案。', inputLabel: '你的技能、可用时间和目标', placeholder: '描述技能、每周可投入的时间和收入目标……' },
  taxstrategy: { label: '税务思路', summary: '值得去问的扣除项和架构方式。', inputLabel: '你的收入和情况', placeholder: '描述收入来源、所在国家/地区，以及是否有公司主体……' },
  invthesis: { label: '投资论据', summary: '一份你敢当面讲出来的投资逻辑。', inputLabel: '标的资产或公司', placeholder: '写明你想分析的公司、资产或行业……' },
  freelancerate: { label: '自由职业报价', summary: '该收多少钱，以及怎么开口。', inputLabel: '你的服务、成本和市场', placeholder: '描述服务内容、经验、成本和目标收入……' },
  symptomcheck: { label: '症状梳理', summary: '弄清你正在经历什么，以及下一步该做什么。', inputLabel: '你的感受', placeholder: '描述症状、持续多久，以及其他相关情况……' },
  sleepopt: { label: '睡眠优化', summary: '基于你真实作息的睡眠方案。', inputLabel: '你的睡眠情况和限制', placeholder: '描述入睡与起床时间、睡眠质量、咖啡因、工作安排和困扰……' },
  workoutgen: { label: '训练计划', summary: '这一周就能照着做的训练安排。', inputLabel: '目标、器械和可用时间', placeholder: '描述目标、训练经验、器械、伤病和每周天数……' },
  nutricoach: { label: '饮食教练', summary: '能熬过真实一周的饮食建议。', inputLabel: '你的目标和饮食习惯', placeholder: '描述目标、现在怎么吃、忌口和做饭时间……' },
  stressdecode: { label: '压力拆解', summary: '先说清压力源，再动手处理它。', inputLabel: '让你有压力的事', placeholder: '描述正在发生什么，以及它如何影响你……' },
  selfcareplan: { label: '自我照顾计划', summary: '没有泡澡蜡烛那一套的照顾方案。', inputLabel: '你的状态和精力', placeholder: '描述当前负荷、精力，以及最近顾不上的事……' },
  mentalperf: { label: '专注力提升', summary: '靠证据而不是偏方,把注意力调清楚。', inputLabel: '你的工作和注意力断点', placeholder: '描述工作内容、注意力什么时候崩，以及试过什么……' },
  anxietytoolkit: { label: '焦虑工具箱', summary: '既应对当下，也处理长期模式。', inputLabel: '你的焦虑是什么样的', placeholder: '描述焦虑什么时候出现、是什么感觉……' },
  cbtexercise: { label: 'CBT 练习', summary: '一次完整走完的思维记录。', inputLabel: '那个想法或情境', placeholder: '描述当时的情境，以及反复出现的那个念头……' },
  burnoutcheck: { label: '倦怠评估', summary: '你在倦怠曲线上的真实位置。', inputLabel: '你的工作量和状态', placeholder: '描述工作量、睡眠、情绪，以及这样持续多久了……' },
  languagetutor: { label: '语言辅导', summary: '一堂课，而不是一串单词。', inputLabel: '语言、水平和目标', placeholder: '说明学哪门语言、目前水平，以及想练什么……' },
  flashcardgen: { label: '记忆卡片', summary: '为回想而做的卡片，不是为眼熟。', inputLabel: '你的材料', placeholder: '贴上想做成卡片的笔记、文本或主题……' },
  studyplan: { label: '复习计划', summary: '按你真正有的时间排的计划。', inputLabel: '科目、截止时间和可用时长', placeholder: '说明学什么、什么时候考，以及每周有多少小时……' },
  conceptmap: { label: '概念地图', summary: '看清各部分之间怎么连起来。', inputLabel: '主题', placeholder: '写明主题，或贴上想梳理的材料……' },
  examprep: { label: '考前冲刺', summary: '接近真题的练习。', inputLabel: '考试和考点', placeholder: '写明考试名称、涉及考点和你目前的水平……' },
  skillroadmap: { label: '技能路线图', summary: '从零到能用，按顺序来。', inputLabel: '技能和你的起点', placeholder: '写明技能、当前水平和每周可投入时间……' },
  socraticlearn: { label: '苏格拉底式学习', summary: '靠一连串好问题把它学懂。', inputLabel: '你想弄懂什么', placeholder: '说明想理解什么，以及你已经知道哪些……' },
  booksummarizer: { label: '读书摘要', summary: '讲清论点，而不是复述腰封。', inputLabel: '书名或正文', placeholder: '写明书名，或贴上想摘要的文本……' },
  feynman73: { label: '费曼讲解', summary: '讲得足够简单，并暴露出知识缺口。', inputLabel: '那个概念', placeholder: '写明想被讲解、或想自测的概念……' },
  quizgen: { label: '出题测验', summary: '一套能找出漏洞的题。', inputLabel: '你的材料', placeholder: '贴上材料，或写明想被考的主题……' },
  storygen2: { label: '故事生成', summary: '一个有结构的故事。', inputLabel: '设定、类型和长度', placeholder: '给出故事前提、类型、调性和篇幅要求……' },
  poemcrafter: { label: '写诗', summary: '讲究手艺的诗，不只是分行。', inputLabel: '主题、形式和情绪', placeholder: '给出主题、想要的形式和情绪……' },
  lyricwrite: { label: '歌词创作', summary: '读得顺、也唱得上口的词。', inputLabel: '曲风、主题和结构', placeholder: '描述曲风、主题、情绪和想要的段落结构……' },
  plottwist: { label: '剧情反转', summary: '早有伏笔的反转。', inputLabel: '你目前的故事', placeholder: '描述故事、人物，以及卡在哪里……' },
  charcreate: { label: '人物设定', summary: '行为逻辑前后一致的角色。', inputLabel: '故事背景和角色定位', placeholder: '描述你的故事，以及这个角色承担什么作用……' },
  worldbuild: { label: '世界观构建', summary: '规则真的能自洽的世界。', inputLabel: '你的设定想法', placeholder: '描述世界设定、类型，以及已有的内容……' },
  screenplayscene: { label: '剧本场景', summary: '格式规范、带潜台词的一场戏。', inputLabel: '场景背景', placeholder: '描述这场戏、人物，以及必须发生什么……' },
  memoirdraft: { label: '回忆录草稿', summary: '把记忆写到纸上，并写出意义。', inputLabel: '那段记忆', placeholder: '描述想写的那段记忆、时期或那个人……' },
  villainorigin: { label: '反派前史', summary: '逻辑站得住脚的反派。', inputLabel: '你的反派', placeholder: '描述这个反派、他的位置和故事世界……' },
  bookblurb: { label: '图书简介', summary: '能把书卖出去的封底文案。', inputLabel: '你的书', placeholder: '描述类型、前提、主角和赌注……' },
  ailawyer: { label: '法律参谋', summary: '弄清你的法律处境和可选项。', inputLabel: '你的情况', placeholder: '描述法律状况、适用地区，以及你想要的结果……' },
  leasereview: { label: '租约审阅', summary: '这份租约到底让你承担了什么。', inputLabel: '租约文本', placeholder: '贴上关键条款或整份合同……' },
  willgen: { label: '遗嘱草稿', summary: '一份可以带去找律师的清晰草稿。', inputLabel: '你的意愿和情况', placeholder: '描述资产、家庭情况、意愿和适用地区……' },
  disputeletter: { label: '争议函', summary: '一封能留下书面记录的争议函。', inputLabel: '争议内容', placeholder: '描述争议经过、时间点，以及你的诉求……' },
  tosdecode: { label: '条款解读', summary: '这些条款实际允许对方做什么。', inputLabel: '条款文本', placeholder: '贴上服务条款或隐私政策……' },
  foiarequest: { label: '信息公开申请', summary: '一份不容易被驳回的材料调取申请。', inputLabel: '你想要哪些材料', placeholder: '描述想要的记录，以及由哪个机构保管……' },
  contractdraft: { label: '合同起草', summary: '一份可用的合同草稿，并标出风险条款。', inputLabel: '这笔交易', placeholder: '描述签约双方、工作内容、付款条件和期限……' },
  rightsexplain: { label: '权利说明', summary: '在这个具体处境下你有哪些权利。', inputLabel: '具体情形', placeholder: '描述发生了什么、在哪里，以及你的身份……' },
  ndareview2: { label: '保密协议审阅', summary: '这份 NDA 把你绑住了什么。', inputLabel: 'NDA 文本', placeholder: '贴上对方要你签的保密协议……' },
  smallclaimscoach: { label: '小额诉讼指引', summary: '按规矩把它告到小额法庭。', inputLabel: '你的诉求', placeholder: '描述纠纷、金额、证据和管辖地……' },
  datingbio: { label: '交友简介', summary: '一份听起来就是你本人的交友资料。', inputLabel: '关于你和使用的 App', placeholder: '描述你自己、兴趣爱好，以及用的是哪个 App……' },
  dateplanner: { label: '初次约会安排', summary: '一份留有体面退场余地的约会计划。', inputLabel: '城市、兴趣和预算', placeholder: '说明城市、兴趣、预算和时间段……' },
  breakuprecover: { label: '分手复原', summary: '不用假装没事地走过去。', inputLabel: '发生了什么', placeholder: '描述这段关系、怎么结束的，以及你现在的状态……' },
  flirtytext: { label: '暧昧消息', summary: '有分寸、不让人反感的暧昧消息。', inputLabel: '你在和谁聊、什么氛围', placeholder: '描述对方、你们怎么认识的，以及目前的氛围……' },
  lovelanguage: { label: '爱的表达方式', summary: '你们各自如何表达和理解在意。', inputLabel: '你们的相处情况', placeholder: '描述你和伴侣如何表达、又期待怎样的在意……' },
  apologyletter: { label: '道歉信', summary: '一封真正承担责任的道歉。', inputLabel: '发生了什么', placeholder: '描述你做了什么、对谁，以及想修复什么……' },
  breakupletter: { label: '分手信', summary: '讲清楚，也不残忍。', inputLabel: '这段关系和你的理由', placeholder: '描述这段关系、持续多久，以及为什么结束……' },
  griefcoach: { label: '哀伤陪伴', summary: '陪你待着，而不是劝你往前看。', inputLabel: '你的失去', placeholder: '描述你失去了什么，以及现在怎么撑着……' },
  conflictresolve: { label: '冲突调解', summary: '找到一条走出争执的路。', inputLabel: '这场冲突', placeholder: '描述冲突、双方立场，以及你想要的结果……' },
  therapyletter: { label: '倾诉信', summary: '一封为了被理解而写的信。', inputLabel: '写给谁、你想说什么', placeholder: '说明这封信写给谁，以及一直没能说出口的话……' },
  deepworkplan: { label: '深度工作规划', summary: '围绕你最难那部分工作安排的一周。', inputLabel: '你的工作和日程', placeholder: '描述工作内容、会议、精力节奏，以及哪些需要深度专注……' },
  meetingsum: { label: '会议纪要', summary: '别人真的会读的纪要。', inputLabel: '你的会议记录或转写稿', placeholder: '贴上原始记录或会议转写……' },
  standupwriter: { label: '每日站会汇报', summary: '简短清楚的站会更新。', inputLabel: '你做了什么、接下来做什么', placeholder: '列出做了什么、下一步是什么，以及有什么阻塞……' },
  weeklyreview: { label: '周度复盘', summary: '能改变下一周的复盘。', inputLabel: '你的这一周', placeholder: '描述这周过得怎么样、完成了什么、哪些落下了……' },
  habitjournal: { label: '习惯记录', summary: '用一种能坚持下去的方式记录习惯。', inputLabel: '那个习惯', placeholder: '描述你想养成或戒掉的习惯，以及所处情境……' },
  lifegoals: { label: '人生目标规划', summary: '有第一步、也有日期的目标。', inputLabel: '你想要什么', placeholder: '描述未来一年或几年你想实现什么……' },
  moodtracker: { label: '情绪追踪', summary: '看清这段时间情绪的规律。', inputLabel: '你的情绪记录', placeholder: '贴上情绪记录，或描述过去这几周……' },
  energymapper: { label: '精力地图', summary: '把工作安排到精力对得上的时段。', inputLabel: '你的一天和精力变化', placeholder: '描述典型的一天，以及精力何时上升、何时下滑……' },
  procbust: { label: '拖延破解', summary: '你为什么在躲它，以及从哪里切入。', inputLabel: '你在逃避什么', placeholder: '描述那件一直拖着的事，以及它带来的感受……' },
  secondbrainai: { label: '第二大脑', summary: '把散落的笔记变成能用的东西。', inputLabel: '你的笔记或系统', placeholder: '描述笔记、使用的工具，以及总是丢失什么……' },
  bizplan: { label: '商业计划', summary: '一份带数字的商业计划。', inputLabel: '你的生意构想', placeholder: '描述业务、客户、产品，以及目前进展……' },
  competitorspy: { label: '竞品分析', summary: '把对手认真读一遍。', inputLabel: '竞争对手和你的市场', placeholder: '写明竞争对手，以及你的产品或所在市场……' },
  pricingstrat: { label: '定价策略', summary: '一个讲得出理由的价格。', inputLabel: '你的产品和市场', placeholder: '描述产品、成本、客户和竞品价格……' },
  gtmplan: { label: '冷启动规划', summary: '最早的客户到底从哪里来。', inputLabel: '产品和目标客户', placeholder: '描述产品、目标客户和你手上的资源……' },
  okrbuilder: { label: 'OKR 制定', summary: '可衡量的目标与关键结果。', inputLabel: '你的目标和周期', placeholder: '描述目标、团队和考核周期……' },
  startupnamer: { label: '公司起名', summary: '真的还能注册到的名字。', inputLabel: '你的公司做什么', placeholder: '描述产品、受众，以及命名上的偏好……' },
  pitchdeckbuild: { label: '融资 BP', summary: '一份有叙事的融资材料。', inputLabel: '你的公司', placeholder: '描述公司、进展、市场和本轮融资……' },
  mvpdesign: { label: 'MVP 设计', summary: '值得动手做的最小那一版。', inputLabel: '你的产品构想', placeholder: '描述产品想法和要解决的用户问题……' },
  exitplanner: { label: '退出规划', summary: '为出售或退出做好准备。', inputLabel: '你的业务和目标', placeholder: '描述业务、经营数据和退出目标……' },
  pricingpage95: { label: '定价页设计', summary: '一个能转化的定价页。', inputLabel: '你的产品和套餐档位', placeholder: '描述产品、各档位，以及每档面向谁……' },
  roastgen: { label: '吐槽生成', summary: '真的有包袱的吐槽。', inputLabel: '吐槽对象', placeholder: '描述要吐槽的人、事或情境……' },
  emailroastv2: { label: '邮件吐槽', summary: '先把你的邮件损一顿，再帮你改好。', inputLabel: '那封邮件', placeholder: '贴上想被吐槽的邮件……' },
  dreaminterp: { label: '解梦', summary: '对你这个梦的一种解读，并说明边界。', inputLabel: '你的梦', placeholder: '尽量详细地描述这个梦……' },
  excusegen: { label: '借口生成', summary: '一个可信、且有分寸的借口。', inputLabel: '你想推掉什么', placeholder: '描述你想推掉什么事、对谁说……' },
  manifesto: { label: '宣言写作', summary: '一份有信念感的宣言。', inputLabel: '你主张什么', placeholder: '描述你相信什么、反对什么……' },
  futureself: { label: '写给未来的自己', summary: '一封留到以后再拆的信。', inputLabel: '你现在的处境', placeholder: '描述你现在的状态，以及打算什么时候读它……' },
  complimentengine: { label: '夸人引擎', summary: '具体、说到点上的夸奖。', inputLabel: '你想夸谁', placeholder: '描述这个人，以及你欣赏他什么……' },
  satiregen: { label: '讽刺写作', summary: '有靶子也有观点的讽刺。', inputLabel: '你的题材', placeholder: '描述想讽刺的对象或现象……' },
  bedtimestory: { label: '睡前故事', summary: '一个能把人哄睡着的故事。', inputLabel: '孩子年龄和主题', placeholder: '说明年龄、想要的角色或主题，以及讲多长……' },
  secretadmirer: { label: '匿名心意', summary: '有分寸、不越界的一封心意。', inputLabel: '写给谁', placeholder: '描述这个人，以及你被什么吸引……' },
  videoanal: { label: '视频拆解', summary: '从转写稿拆解一支视频。', inputLabel: '转写稿或内容描述', placeholder: '贴上转写稿、字幕，或对视频的详细描述……' },
  meetingtrans: { label: '会议洞察', summary: '把转写稿变成决策和负责人。', inputLabel: '会议转写稿', placeholder: '贴上会议转写或详细记录……' },
  skillbuilder: { label: '技能训练', summary: '为了真正练成而设计的练习。', inputLabel: '技能和你的水平', placeholder: '写明技能、当前水平和可用练习时间……' },
};

export function dreamCategoryLabel(category: string, zh: boolean): string {
  return zh ? DREAM_TOOL_CATEGORY_ZH[category] || category : category;
}

export function localizeDreamTool<T extends { id: string; label: string; summary: string; inputLabel: string; placeholder: string; category: string }>(tool: T, zh: boolean): T {
  if (!zh) return tool;
  const text = DREAM_TOOL_ZH[tool.id];
  if (!text) return { ...tool, category: dreamCategoryLabel(tool.category, true) };
  return { ...tool, label: text.label, summary: text.summary, inputLabel: text.inputLabel, placeholder: text.placeholder, category: dreamCategoryLabel(tool.category, true) };
}

// Text a search box should match against, so typing Chinese or English both work.
export function dreamSearchText(tool: { id: string; label: string; summary: string; category: string }): string {
  const text = DREAM_TOOL_ZH[tool.id];
  return [tool.label, tool.summary, tool.category, DREAM_TOOL_CATEGORY_ZH[tool.category] || '', text ? text.label : '', text ? text.summary : ''].join(' ').toLowerCase();
}
